In [1]:
import random

import numpy as np
import scipy as sp

import scipy.linalg
import scipy.optimize

import matplotlib.pyplot as plt
%matplotlib inline

import seaborn as sns
sns.set_style("white")
sns.set_context("talk")

/Users/vminden/anaconda/envs/py3k/lib/python3.5/site-packages/matplotlib/__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))


In [2]:
from markovc import *

In [3]:
from data import *

In [4]:
alpha = 0.3
x = [alpha, 1-alpha, alpha*0.5]
Q = create_rate_matrix_from_vector(x)

P = embedded_jump_chain(Q)
pi = equi_dtmc(P)
P

array([[ 0.        ,  0.3       ,  0.7       ],
       [ 0.82352941,  0.        ,  0.17647059],
       [ 0.26086957,  0.73913043,  0.        ]])

In [5]:
equi_deriv_ctmc(Q, P, pi, (0,1))

[[-1.    0.3   0.7 ]
 [ 0.7  -0.85  0.15]
 [ 0.3   0.85 -1.15]]


array([ 0.39407949, -0.56080543,  0.16672594])

In [ ]:
def nll(xhat, data):
    Qhat = create_rate_matrix_from_vector(xhat)
    
    s = 0
    for (winner, choices), count in data.items():
#         print("{} {} {}".format(winner, choices, count))
        winner_idx = [idx for idx, val in enumerate(choices) if winner==val][0]
        Qs = submatrix(Qhat, choices)
        try:
            piS = equi_ctmc(Qs)[winner_idx]
        except ValueError:
            print(xhat)
            raise
        
#         print(piS)

        s += count * np.log(np.abs(piS))    
        
    return -s

In [ ]:
data = gen_data(Q, 5000)
x0 = [random.random() for _ in range(len(x))]

res = sp.optimize.minimize(lambda x: nll(x, data), x0, method="L-BFGS-B", bounds=[(0.0001, 0.9999) for _ in range(len(x0))])
print(res)

In [ ]:
xopt = res['x']
Qhat = create_rate_matrix_from_vector(xopt)

In [ ]:
Qhat

In [ ]:
Phat = embedded_jump_chain(Qhat)
pihat = equi_ctmc(Qhat)

In [ ]:
equi_deriv_ctmc(Qhat, Phat, pihat, (2, 1))

In [ ]:
nll(xopt, data)

In [ ]:
gen_data(Q, n=100, pinc=0.2)

In [ ]:
n = 3

In [ ]:
m = n * (n-1) / 2

In [ ]:
import math

In [ ]:
int(1/2 + math.sqrt(1/4 + 2 * m)+0.5)